# Generated by Django 5.0.7 on 2025-09-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fitment',
            fields=[
                ('hash', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('partId', models.CharField(max_length=64)),
                ('itemStatus', models.CharField(default='Active', max_length=32)),
                ('itemStatusCode', models.IntegerField(default=0)),
                ('baseVehicleId', models.CharField(max_length=64)),
                ('year', models.IntegerField()),
                ('makeName', models.CharField(max_length=64)),
                ('modelName', models.CharField(max_length=64)),
                ('subModelName', models.CharField(max_length=64)),
                ('driveTypeName', models.CharField(max_length=32)),
                ('fuelTypeName', models.CharField(max_length=32)),
                ('bodyNumDoors', models.IntegerField()),
                ('bodyTypeName', models.CharField(max_length=64)),
                ('ptid', models.CharField(max_length=32)),
                ('partTypeDescriptor', models.CharField(max_length=128)),
                ('uom', models.CharField(max_length=16)),
                ('quantity', models.IntegerField(default=1)),
                ('fitmentTitle', models.CharField(max_length=200)),
                ('fitmentDescription', models.TextField(blank=True, null=True)),
                ('fitmentNotes', models.TextField(blank=True, null=True)),
                ('position', models.CharField(max_length=64)),
                ('positionId', models.IntegerField()),
                ('liftHeight', models.CharField(max_length=32)),
                ('wheelType', models.CharField(max_length=64)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.CharField(default='system', max_length=64)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('updatedBy', models.CharField(default='system', max_length=64)),
            ],
            options={
                'indexes': [models.Index(fields=['partId'], name='fitments_fi_partId_675464_idx'), models.Index(fields=['makeName'], name='fitments_fi_makeNam_913e38_idx'), models.Index(fields=['modelName'], name='fitments_fi_modelNa_db3853_idx'), models.Index(fields=['year'], name='fitments_fi_year_d7f27e_idx'), models.Index(fields=['updatedAt'], name='fitments_fi_updated_9ca58d_idx')],
            },
        ),
    ]
