# Generated by Django 5.0.7 on 2025-09-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitment',
            name='fitmentType',
            field=models.CharField(choices=[('manual_fitment', 'Manual Fitment'), ('potential_fitment', 'Potential Fitment'), ('ai_fitment', 'AI Fitment')], default='manual_fitment', max_length=50),
        ),
    ]
