# Generated by Django 5.0.7 on 2025-09-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitments', '0002_fitment_fitmenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitment',
            name='deletedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fitment',
            name='deletedBy',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='fitment',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
