# Generated by Django 5.0.7 on 2025-09-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitments', '0004_fitmentuploadsession_fitmentvalidationresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='PotentialVehicleConfiguration',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('vehicle_id', models.CharField(max_length=100)),
                ('base_vehicle_id', models.CharField(max_length=64)),
                ('body_style_config', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('make', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=64)),
                ('submodel', models.CharField(max_length=64)),
                ('drive_type', models.CharField(max_length=32)),
                ('fuel_type', models.CharField(max_length=32)),
                ('num_doors', models.IntegerField()),
                ('body_type', models.CharField(max_length=64)),
                ('relevance', models.IntegerField(default=0)),
                ('recommendation_method', models.CharField(choices=[('similarity', 'Similarity Analysis'), ('base-vehicle', 'Base Vehicle Analysis')], default='similarity', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'potential_vehicle_configurations',
                'indexes': [models.Index(fields=['make', 'model', 'year'], name='potential_v_make_f892bc_idx'), models.Index(fields=['base_vehicle_id'], name='potential_v_base_ve_c030f7_idx'), models.Index(fields=['relevance'], name='potential_v_relevan_e90e75_idx'), models.Index(fields=['recommendation_method'], name='potential_v_recomme_76f958_idx')],
            },
        ),
    ]
