# Generated by Django 5.0.7 on 2025-09-17 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitments', '0005_potentialvehicleconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitment',
            name='dynamicFields',
            field=models.JSONField(blank=True, default=dict, help_text='Dynamic fields from VCDB and Product configurations'),
        ),
    ]
