# Generated by Django 5.0.7 on 2025-09-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitments', '0007_fitment_dynamicfields_improved'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitment',
            name='aiDescription',
            field=models.TextField(blank=True, help_text='AI-generated description explaining the fitment reasoning and analysis', null=True),
        ),
        migrations.AddField(
            model_name='fitment',
            name='confidenceScore',
            field=models.FloatField(blank=True, help_text='AI confidence score (0.0 to 1.0) indicating the reliability of the fitment', null=True),
        ),
    ]
