# Generated by Django 4.2.3 on 2025-09-23 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_tenant_options_tenant_ai_instructions_and_more'),
        ('fitments', '0008_fitment_aidescription_fitment_confidencescore'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitment',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fitments', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='fitmentuploadsession',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fitment_upload_sessions', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='potentialvehicleconfiguration',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='potential_vehicle_configurations', to='tenants.tenant'),
        ),
    ]
