# Generated by Django 5.0.7 on 2025-10-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitments', '0009_fitment_tenant_fitmentuploadsession_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitment',
            name='ai_job_id',
            field=models.UUIDField(blank=True, help_text='Reference to AiFitmentJob if created by AI', null=True),
        ),
    ]
