# Generated by Django 4.2.3 on 2025-10-06 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_make_slug_optional'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productdata',
            name='unique_tenant_part_number',
        ),
        migrations.AlterField(
            model_name='productdata',
            name='configuration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_data', to='products.productconfiguration'),
        ),
        migrations.AlterField(
            model_name='productdata',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_data', to='tenants.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='productdata',
            unique_together={('tenant', 'part_number')},
        ),
    ]
