# Generated by Django 4.2.3 on 2025-09-23 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['name'], 'verbose_name': 'Entity', 'verbose_name_plural': 'Entities'},
        ),
        migrations.AddField(
            model_name='tenant',
            name='ai_instructions',
            field=models.TextField(blank=True, help_text='Default AI instructions for this entity', null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='company_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tenants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenant',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the entity/company', null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='fitment_settings',
            field=models.JSONField(blank=True, default=dict, help_text='Entity-level fitment settings and preferences'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Default entity for new users'),
        ),
    ]
