# Generated by Django 4.2.3 on 2025-10-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_make_slug_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='default_fitment_method',
            field=models.CharField(choices=[('manual', 'Manual'), ('ai', 'AI')], default='manual', help_text='Default fitment method for this entity', max_length=20),
        ),
    ]
