# Generated by Django 4.2.3 on 2025-10-06 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vcdb_categories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vcdbdata',
            name='tenant',
        ),
        migrations.AlterUniqueTogether(
            name='vcdbcategory',
            unique_together={('name', 'version')},
        ),
        migrations.RemoveField(
            model_name='vcdbcategory',
            name='tenant',
        ),
    ]
