# Generated by Django 5.0.7 on 2025-09-08 11:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('attribute_priorities', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presets', to='tenants.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=400)),
                ('content_type', models.CharField(max_length=120)),
                ('storage_url', models.TextField()),
                ('file_size_bytes', models.IntegerField()),
                ('status', models.CharField(default='received', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('preset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.preset')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='NormalizationResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_index', models.IntegerField()),
                ('mapped_entities', models.JSONField()),
                ('confidence', models.FloatField()),
                ('status', models.CharField(default='pending', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.upload')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(max_length=60)),
                ('status', models.CharField(default='queued', max_length=40)),
                ('params', models.JSONField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='tenants.tenant')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='workflow.upload')),
            ],
        ),
        migrations.CreateModel(
            name='Lineage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=60)),
                ('entity_id', models.UUIDField()),
                ('parent_entity_type', models.CharField(blank=True, max_length=60, null=True)),
                ('parent_entity_id', models.UUIDField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'entity_type', 'entity_id'], name='ix_lineage_tenant_entity')],
            },
        ),
        migrations.AddIndex(
            model_name='upload',
            index=models.Index(fields=['tenant', 'status'], name='ix_upload_tenant_status'),
        ),
        migrations.AddIndex(
            model_name='normalizationresult',
            index=models.Index(fields=['tenant', 'upload', 'status'], name='ix_norm_tenant_upload_status'),
        ),
        migrations.AlterUniqueTogether(
            name='normalizationresult',
            unique_together={('upload', 'row_index')},
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['tenant', 'job_type', 'status'], name='ix_job_tenant_type_status'),
        ),
    ]
