# Generated by Django 5.0.7 on 2025-09-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='checksum',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='file_format',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='preflight_report',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
