# Generated by Django 5.0.7 on 2025-09-08 16:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIFitmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_id', models.CharField(max_length=100)),
                ('part_description', models.TextField()),
                ('year', models.IntegerField()),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('submodel', models.CharField(blank=True, max_length=100)),
                ('drive_type', models.CharField(blank=True, max_length=50)),
                ('position', models.CharField(default='Front', max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('confidence', models.FloatField(default=0.0)),
                ('ai_reasoning', models.TextField()),
                ('is_selected', models.BooleanField(default=False)),
                ('is_applied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-confidence', 'part_id'],
            },
        ),
        migrations.CreateModel(
            name='FitmentUploadSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vcdb_file', models.FileField(upload_to='fitment_uploads/vcdb/')),
                ('products_file', models.FileField(upload_to='fitment_uploads/products/')),
                ('vcdb_filename', models.CharField(max_length=255)),
                ('products_filename', models.CharField(max_length=255)),
                ('vcdb_records', models.IntegerField(default=0)),
                ('products_records', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error')], default='uploading', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppliedFitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_id', models.CharField(max_length=100)),
                ('part_description', models.TextField()),
                ('year', models.IntegerField()),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('submodel', models.CharField(blank=True, max_length=100)),
                ('drive_type', models.CharField(blank=True, max_length=50)),
                ('position', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('ai_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fitment_uploads.aifitmentresult')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_fitments', to='fitment_uploads.fitmentuploadsession')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.AddField(
            model_name='aifitmentresult',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_results', to='fitment_uploads.fitmentuploadsession'),
        ),
    ]
