# Generated by Django 5.0.7 on 2025-09-09 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitment_uploads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aifitmentresult',
            name='position',
            field=models.CharField(blank=True, default='Front', max_length=100, null=True),
        ),
    ]
