# Generated by Django 5.0.7 on 2025-09-10 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_uploads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIFitmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_id', models.CharField(max_length=100)),
                ('part_description', models.TextField()),
                ('year', models.IntegerField()),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('submodel', models.CharField(blank=True, max_length=100)),
                ('drive_type', models.CharField(blank=True, max_length=50)),
                ('position', models.CharField(blank=True, default='Front', max_length=100, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('confidence', models.FloatField(default=0.0)),
                ('ai_reasoning', models.TextField()),
                ('is_selected', models.BooleanField(default=False)),
                ('is_applied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_results', to='data_uploads.datauploadsession')),
            ],
            options={
                'verbose_name': 'AI Fitment Result',
                'verbose_name_plural': 'AI Fitment Results',
                'ordering': ['-confidence', 'part_id'],
            },
        ),
    ]
