# Generated by Django 5.0.7 on 2025-09-10 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_uploads', '0002_aifitmentresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedFitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_id', models.CharField(max_length=100)),
                ('part_description', models.TextField()),
                ('year', models.IntegerField()),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('submodel', models.CharField(blank=True, max_length=100)),
                ('drive_type', models.CharField(blank=True, max_length=50)),
                ('position', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('ai_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_uploads.aifitmentresult')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_fitments', to='data_uploads.datauploadsession')),
            ],
            options={
                'verbose_name': 'Applied Fitment',
                'verbose_name_plural': 'Applied Fitments',
                'ordering': ['-applied_at'],
            },
        ),
    ]
