# Generated by Django 5.0.7 on 2025-09-15 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_uploads', '0003_appliedfitment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('part_id', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(blank=True, max_length=100)),
                ('part_type', models.CharField(blank=True, max_length=100)),
                ('compatibility', models.CharField(blank=True, max_length=100)),
                ('specifications', models.JSONField(blank=True, default=dict)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Data',
                'verbose_name_plural': 'Product Data',
                'ordering': ['part_id'],
            },
        ),
        migrations.CreateModel(
            name='VCDBData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('submodel', models.CharField(blank=True, max_length=100)),
                ('drive_type', models.CharField(blank=True, max_length=50)),
                ('fuel_type', models.CharField(blank=True, max_length=50)),
                ('num_doors', models.IntegerField(blank=True, null=True)),
                ('body_type', models.CharField(blank=True, max_length=100)),
                ('engine_type', models.CharField(blank=True, max_length=100)),
                ('transmission', models.CharField(blank=True, max_length=100)),
                ('trim_level', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'VCDB Data',
                'verbose_name_plural': 'VCDB Data',
                'ordering': ['year', 'make', 'model'],
                'unique_together': {('year', 'make', 'model', 'submodel', 'drive_type')},
            },
        ),
    ]
