# Generated by Django 5.0.7 on 2025-09-15 06:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_uploads', '0004_productdata_vcdbdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backspacing',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'backspacing',
            },
        ),
        migrations.CreateModel(
            name='Fitment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('lift_height', models.CharField(blank=True, max_length=100, null=True)),
                ('wheel_type', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fitments',
            },
        ),
        migrations.CreateModel(
            name='LiftHeight',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'lift_heights',
            },
        ),
        migrations.CreateModel(
            name='TireDiameter',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tire_diameters',
            },
        ),
        migrations.CreateModel(
            name='WheelDiameter',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'wheel_diameters',
            },
        ),
        migrations.CreateModel(
            name='WheelType',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'wheel_types',
            },
        ),
        migrations.CreateModel(
            name='FitmentWheelParameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tire_diameter', models.CharField(blank=True, max_length=50, null=True)),
                ('wheel_diameter', models.CharField(blank=True, max_length=50, null=True)),
                ('backspacing', models.CharField(blank=True, max_length=50, null=True)),
                ('fitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wheel_parameters', to='data_uploads.fitment')),
            ],
            options={
                'db_table': 'fitment_wheel_parameters',
            },
        ),
    ]
