# Generated by Django 5.0.7 on 2025-09-15 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_uploads', '0005_backspacing_fitment_liftheight_tirediameter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitmentwheelparameter',
            name='fitment',
        ),
        migrations.DeleteModel(
            name='Fitment',
        ),
        migrations.DeleteModel(
            name='FitmentWheelParameter',
        ),
    ]
