# Generated by Django 4.2.3 on 2025-09-23 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_tenant_options_tenant_ai_instructions_and_more'),
        ('data_uploads', '0007_add_confidence_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='aifitmentresult',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_fitment_results', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='appliedfitment',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applied_fitments', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='datauploadsession',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_upload_sessions', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='productdata',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_data', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='vcdbdata',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vcdb_data', to='tenants.tenant'),
        ),
    ]
