# Generated by Django 5.0.7 on 2025-09-24 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_uploads', '0002_update_unique_constraints_for_tenant'),
        ('data_uploads', '0008_aifitmentresult_tenant_appliedfitment_tenant_and_more'),
    ]

    operations = [
    ]
