# Generated by Django 5.0.7 on 2025-10-08 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_uploads', '0010_ai_fitment_jobs'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aifitmentjob',
            new_name='data_upload_tenant__eabc9d_idx',
            old_name='data_upload_tenant__status_idx',
        ),
        migrations.RenameIndex(
            model_name='aifitmentjob',
            new_name='data_upload_created_7fe398_idx',
            old_name='data_upload_created_idx',
        ),
        migrations.RenameIndex(
            model_name='aigeneratedfitment',
            new_name='data_upload_job_id_a88164_idx',
            old_name='data_upload_job_status_idx',
        ),
        migrations.RenameIndex(
            model_name='aigeneratedfitment',
            new_name='data_upload_confide_8030da_idx',
            old_name='data_upload_confiden_idx',
        ),
    ]
