# Generated by Django 5.0.7 on 2025-10-08 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_uploads', '0011_rename_data_upload_tenant__status_idx_data_upload_tenant__eabc9d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdata',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Upload session this product belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='data_uploads.datauploadsession'),
        ),
        migrations.AddField(
            model_name='productdata',
            name='source_file_name',
            field=models.CharField(blank=True, help_text='Original filename of the product file', max_length=255),
        ),
    ]
