# Generated by Django 4.2.3 on 2025-10-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_uploads', '0012_productdata_session_productdata_source_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='aifitmentjob',
            name='celery_task_id',
            field=models.CharField(blank=True, help_text='Celery task ID for tracking', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aifitmentjob',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='When job processing started', null=True),
        ),
        migrations.AlterField(
            model_name='aifitmentjob',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('review_required', 'Review Required')], default='queued', max_length=20),
        ),
    ]
