# Generated by Django 4.2.3 on 2025-10-16 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vcdb', '0001_initial'),
    ]

    operations = [
    ]
