# Generated by Django 4.2.3 on 2025-10-16 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vcdb', '0002_auto_20251016_0717'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationStage',
            fields=[
                ('publication_stage_id', models.IntegerField(primary_key=True, serialize=False)),
                ('publication_stage_name', models.CharField(max_length=100)),
                ('culture_id', models.CharField(default='en-US', max_length=10)),
                ('effective_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Publication Stage',
                'verbose_name_plural': 'Publication Stages',
                'db_table': 'vcdb_publicationstage',
                'ordering': ['publication_stage_name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.IntegerField(primary_key=True, serialize=False)),
                ('region_name', models.CharField(max_length=100)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('region_abbr', models.CharField(max_length=10)),
                ('culture_id', models.CharField(default='en-US', max_length=10)),
                ('effective_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
                'db_table': 'vcdb_region',
                'ordering': ['region_name'],
            },
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='publication_stage_id',
            field=models.ForeignKey(db_column='publication_stage_id', on_delete=django.db.models.deletion.CASCADE, to='vcdb.publicationstage'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='region_id',
            field=models.ForeignKey(db_column='region_id', on_delete=django.db.models.deletion.CASCADE, to='vcdb.region'),
        ),
    ]
