# Generated by Django 4.2.3 on 2025-10-16 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vcdb', '0003_publicationstage_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('year_id', models.IntegerField(primary_key=True, serialize=False)),
                ('effective_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Year',
                'verbose_name_plural': 'Years',
                'db_table': 'vcdb_year',
                'ordering': ['year_id'],
            },
        ),
        migrations.AlterField(
            model_name='basevehicle',
            name='year_id',
            field=models.ForeignKey(db_column='year_id', on_delete=django.db.models.deletion.CASCADE, to='vcdb.year'),
        ),
    ]
