# Generated by Django 5.0.7 on 2025-09-16 07:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Field name (will be used as column name)', max_length=100)),
                ('display_name', models.CharField(help_text='Human-readable display name', max_length=150)),
                ('description', models.TextField(blank=True, help_text='Field description for users')),
                ('field_type', models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('boolean', 'Boolean'), ('enum', 'Enum'), ('date', 'Date'), ('text', 'Text'), ('decimal', 'Decimal'), ('integer', 'Integer')], default='string', max_length=20)),
                ('reference_type', models.CharField(choices=[('vcdb', 'VCDB'), ('product', 'Product'), ('both', 'Both')], help_text='Where this field applies (VCDB, Product, or Both)', max_length=10)),
                ('requirement_level', models.CharField(choices=[('required', 'Required'), ('optional', 'Optional'), ('disabled', 'Disabled')], default='optional', help_text='Whether field is required, optional, or disabled', max_length=10)),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether this field is currently active')),
                ('is_unique', models.BooleanField(default=False, help_text='Whether field values must be unique')),
                ('min_length', models.IntegerField(blank=True, help_text='Minimum length for string/text fields', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_length', models.IntegerField(blank=True, help_text='Maximum length for string/text fields', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('min_value', models.DecimalField(blank=True, decimal_places=6, help_text='Minimum value for numeric fields', max_digits=20, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=6, help_text='Maximum value for numeric fields', max_digits=20, null=True)),
                ('enum_options', models.JSONField(blank=True, default=list, help_text='Available options for enum fields')),
                ('default_value', models.TextField(blank=True, help_text='Default value for this field')),
                ('display_order', models.IntegerField(default=0, help_text='Order for displaying fields in forms')),
                ('show_in_filters', models.BooleanField(default=True, help_text='Whether to show this field in filter forms')),
                ('show_in_forms', models.BooleanField(default=True, help_text='Whether to show this field in data entry forms')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('updated_by', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Field Configuration',
                'verbose_name_plural': 'Field Configurations',
                'ordering': ['reference_type', 'display_order', 'name'],
                'unique_together': {('name', 'reference_type')},
            },
        ),
        migrations.CreateModel(
            name='FieldConfigurationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('enabled', 'Enabled'), ('disabled', 'Disabled')], max_length=10)),
                ('changed_by', models.CharField(max_length=100)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True)),
                ('field_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='field_config.fieldconfiguration')),
            ],
            options={
                'verbose_name': 'Field Configuration History',
                'verbose_name_plural': 'Field Configuration Histories',
                'ordering': ['-changed_at'],
            },
        ),
    ]
