# Generated by Django 5.0.7 on 2025-09-16 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldconfigurationhistory',
            name='field_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='fieldconfigurationhistory',
            name='field_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='field_config.fieldconfiguration'),
        ),
    ]
