# Generated by Django 4.2.3 on 2025-09-23 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_tenant_options_tenant_ai_instructions_and_more'),
        ('field_config', '0002_fieldconfigurationhistory_field_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fieldconfiguration',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='fieldconfiguration',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_configurations', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='fieldconfigurationhistory',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_configuration_history', to='tenants.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='fieldconfiguration',
            unique_together={('tenant', 'name', 'reference_type')},
        ),
    ]
